server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.15.1
  server:
    renewalPercentThreshold: 0.45
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
